// 22MD_Nextjs13-Search-Filter/app/components/Button/Button.tsx
import styles from './Button.module.scss';

type TButtonProps = {
    type: 'button' | 'submit';
    onClick?: () => void;
    label: string;
    disabled?: boolean;
}

const Button = (props: TButtonProps) => {
    const {
        label,
        onClick,
        type,
        disabled,
    } = props;
    return (
        <>
            <button
                className={styles.button}
                type={type}
                onClick={onClick}
                disabled={disabled}
            >
                {label}
            </button>
        </>
    );
};

export default Button;

// 25MD_Angular_Router-Ngrx/25_Angular/src/app/components/button/button.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-button',
    templateUrl: './button.component.html',
    styleUrls: ['./button.component.scss'],
})
export class ButtonComponent {
  @Input() label = '';

  @Input() type: 'button' | 'submit' = 'submit';

  @Input() disabled: boolean;
}

<button
    class="button"
    [type]="type"
    [disabled]="disabled"
>
    {{ label | uppercase }}
</button>
